### ISSUE TITLE
Unwrap and Option methods

### ISSUE THREAD

**Issue by TylerBloom** [crwn1337/enum_helpers#1]
I've had a similar idea for a crate for a while, and this seems solid! Two things that would be nice to see are `unwrap_*` and `opt_*` (or another name) methods. Particularly for tests, it would be nice to these kinds of lines:
```rust
let MyEnum::Variant(data) = thing else { panic!() };
```
With this:
```rust
let data = thing.unwrap_variant();
```

Similarly, it would be nice to convert enums into options. Ideally, these methods would be called `as_*`, reference methods would be `as_ref_*`, and mutable methods would be `as_mut_*`. Though, a different name, such as `opt_*` might work too.

**Comment by crwn1337** [comment]
If I understood you correctly, you want functions such as `unwrap_x` where x is the enum? Yeah, that sounds perfect, but I don't get what you mean by the 2nd part, could you describe it in more detail or give code examples?

**Comment by TylerBloom** [comment]
Yes, that is what I'm describing in the first half, the ability to "unwrap" a particular variant (similar to `Result::unwrap`  and `Result::unwrap_err`).

For the second half, if I understand this correctly, an enum that has `EnumAs` will (roughly) generate this code:
```rust
// This enum
#[derive(EnumAs)]
enum MyEnum {
  Foo(u8),
  Bar(String),
}

// has this code generated for it
impl MyEnum {
  pub fn as_foo(&self) -> Option<&u8> { .. }
  pub fn as_bar(&self) -> Option<&String> { .. }
}
```
Similarly, `EnumAsMut` will generate code where the methods take `&mut self` and return `Option<&mut T>`. I would like methods that consume the enum and return an option of the owned inner data. This would look something like this:
```rust
// This enum
#[derive(EnumAsOpt)]
enum MyEnum {
  Foo(u8),
  Bar(String),
}

// has this code generated for it
impl MyEnum {
  pub fn as_foo(self) -> Option<u8> { .. }
  pub fn as_bar(self) -> Option<String> { .. }
}
```

**Comment by crwn1337** [comment]
Ah, I see, I don't know if implementing that with `Option<_>` is a good idea, since if it's `None` it will still consume it, but I don't know a better way of doing it without panicking which is considered a bad practice for a library.

I would probably implement it like this:
```rust
#[derive(EnumInto)]
pub enum MyEnum {
    Foo(u8),
    Bar(String),
}

// generates this:
impl MyEnum {
    pub fn into_foo(self) -> Option<u8> {
        match self {
            MyEnum::Foo(x) => Some(x),
            _ => None,
        }
    }

    pub fn into_bar(self) -> Option<String> {
        match self {
            MyEnum::Bar(x) => Some(x),
            _ => None,
        }
    }
}

**Comment by TylerBloom** [comment]
Yes, that's exactly how I would implement it. The point of these "into `Option`" methods is similar to that of `Result::ok`. You use them where you only care about the data in a particular variant and want easy access to all of the helpful methods on `Option` (including access to the try operator).

**Comment by crwn1337** [comment]
Done in https://github.com/crwn1337/enum_helpers/commit/60f2a81a2a444f59fe1eee274d682463524c84e9

**Comment by TylerBloom** [comment]
The `into` implementation looks good, but there is not an `unwrap` implementation.

**Comment by crwn1337** [comment]
I decided against it since I didn't see any use in making an extra proc macro for just calling `.unwrap()`, since people might misuse it accidentally.

**Comment by TylerBloom** [comment]
Obviously, this is your crate, and you can do with it what you see fit. But I would encourage against this line of thinking. Such methods exist for a reason. Each class of methods (`is_`, `as_`, etc.) are opt-in. It is not unreasonable to expect users to know what `EnumUnwrap` does and to understand the risks of these methods, especially since these methods follow the same naming convention as the standard library.

Personally, my main interest in the unwrap methods is for testing, where panicking with minimal boilerplate is ideal.

**Comment by crwn1337** [comment]
I understand why you would want it, but panicking in a library isn't ideal even when it's documented, and while it's true that the standard library contains functions that could panic if misused, it is still preferable to let the user handle errors rather than having an unexpected panic because they didn't read the documentation.

**Comment by TylerBloom** [comment]
> panicking in a library isn't ideal even when it's documented

It's true that a library should avoid panics as much as possible. Even when it's documented, it is possible to miss that fact. In such cases, panics are an unfortunate side event. That is not the case here. The idea behind unwrapping is that the panics are a feature, not a bug.

Again, this is your repo, and this is the last I have to say. I'm just asking for you to approach this with a bit more nuance.
